# Generated by Django 6.0.2 on 2026-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_trafficsource_remove_designation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeauthor',
            name='role',
            field=models.CharField(default='Author', max_length=50),
        ),
    ]
